language: r
warnings_are_errors: true
sudo: required

env:
 global:
   - CRAN: http://cran.rstudio.com

r_binary_packages:
 - rjags

r_github_packages:
 - poissonconsulting/tulip
 - poissonconsulting/datalist
 - poissonconsulting/juggler
 - poissonconsulting/jaggernaut
 - poissonconsulting/ranmrdata

notifications:
  email:
    on_success: change
    on_failure: change
